parameters:
    database_driver: pdo_mysql
    database_host: database
    database_port: null
    database_name: concerto
    database_user: root
    database_password: root
    database_path: null
    database_unix_socket: null
    database_version: mysql:8.0
    locale: de_DE