services:
    database:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      container_name: database
      restart: unless-stopped
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${DATABASE_NAME}
        - DATABASE_HOST=${DATABASE_HOST}
        - DATABASE_PORT=${DATABASE_PORT}
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_USER=${DATABASE_USER}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - TZ=Europe/Berlin
      volumes:
        - ./database/mysql:/var/lib/mysql
        - ./database/conf/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
        - ./logs/database:/var/log/mysql
      ports:
        - "3306:3306"

    concerto:
      build:
        context: ..
        dockerfile: Dockerfile
      container_name: concerto
      restart: unless-stopped
      depends_on:
        - database
      environment:
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}

      volumes:
        - ./startup.sh:/startup.sh
        - ./logs/concerto/nginx:/var/log/nginx
        - ./logs/concerto/php-fpm:/var/log/php-fpm
        - ./logs/concerto/app:/usr/src/concerto/var/logs
        - ./concerto/nginx/sites:/etc/nginx/sites-available
        - ./logs/concerto/sessions:/usr/src/concerto/src/Concerto/TestBundle/Resources/sessions
        - ./concerto/nginx/sites/concerto.conf:/etc/nginx/sites-available/concerto.conf
      ports:
        - "8090:80"
      command: ["bash", "/startup.sh"]
