version: '3.0'
services:
    database:
      image: mysql:8.4
      container_name: database
      restart: unless-stopped
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=concerto
        - TZ=Europe/Berlin
      volumes:
        - ./database/mysql:/var/lib/mysql
        - ./database/conf/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
        - ./logs/database:/var/log/mysql
      ports:
        - "3306:3306"

    concerto:
      build:
        context: ..
        dockerfile: Dockerfile
      container_name: concerto
      restart: unless-stopped
      depends_on:
        - database
      volumes:
        - ./logs/concerto/nginx:/var/log/nginx
        - ./logs/concerto/php-fpm:/var/log/php-fpm
        - ./logs/concerto/app:/usr/src/concerto/var/logs
        - ./logs/concerto/sessions:/usr/src/concerto/src/Concerto/TestBundle/Resources/sessions
      ports:
        - "8090:80"
